### ISSUE TITLE
Integrating visual testing (to inspect OpenMojis for dark mode usage)

### ISSUE THREAD

**Issue by stephanbogner** [hfg-gmuend/openmoji-tester#14]
@b-g 

## 1 - Landing page
As we discussed I split the process up in steps (1, 2 and 3).
Phrasing could use some work but you can now start the Mocha-test and the visual test separately from each other.

<img width="1019" alt="Screenshot 2022-06-01 at 10 28 32" src="https://user-images.githubusercontent.com/7897006/171362015-115eccc3-0810-4be4-b38e-180bd6246b4e.png">

## 2 - Visual test
The visual test is now separate from the mocha test and includes a bit of guideline for good and bad outlining examples.

<img width="867" alt="Screenshot 2022-06-01 at 10 28 03" src="https://user-images.githubusercontent.com/7897006/171362048-7f3bba0f-49bd-4433-b14a-6d48e889bf2c.png">

## Branch
You can find the code in the [outlining branch](https://github.com/hfg-gmuend/openmoji-tester/tree/outlining).

Let me know if you have any remarks 🙂

**Comment by b-g** [comment]
@stephanbogner Nice!! Great! Just:
- I would find it better if the entire "OpenMoji Visual Dark Mode Check" would look dark e.g. had a dark background entirely
- and I would adjust wording:

------------

This is a small helper web app which lets you check quickly whether your OpenMoji svg file plays nicely on a dark background and meets the technical requirements of the OpenMoji Styleguide. Every svg file is tested on things like: colors, layer, names, size ... and you asked in step 3 to validate with your own eyes if your design works also on a dark background.

## 2. Styleguide Check
All of your svg files have to produce green tests only. Fix your files until everything is green! Please! :)

## 3. Dark Mode Check
Every OpenMoji has to work in dark mode too. Make sure that the generated white outline looks as in the stated examples. Please adjust your file until the OpenMoji looks well designed even if in use on a dark background. 

------------

OpenMoji Visual Dark Mode Check • Results
Does the generated white outline of your OpenMoji look good?

**Comment by stephanbogner** [comment]
@b-g I did the changes, please have a look.

PS: I only slightly changed the phrasing, where I thought it would flow nicer.
PPS: I just tested the "old" tester and it works fine on my machine (even after deleting dependencies and running npm install) – please check if the issue still persists.

**Comment by stephanbogner** [comment]
@b-g

Did you grant me access to the Glitch project?
My account is: [glitch.com/@stephanbogner](https://glitch.com/@stephanbogner) (because the openmoji-tester project doesn't appear in my account)

But in any case [I found the issue and it should really be fixed now](https://github.com/hfg-gmuend/openmoji-tester/commit/f59f971f91ebd1ec2152ec40f6f48b8e85386c37) 🤞:
It was really hard to find because it was really dumb 😆 (I imported lodash wrongly, but for some reason it didn't throw any errors, it just didn't do anything with the OpenMoji-json)

**Comment by b-g** [comment]
Many thanks! Fixed, works on Glitch now as well. Yay! (Did send you an invite as well). Yay! Done!
